# =============================================================================
# PF-CORE MVP CI/CD Pipeline
# =============================================================================
# Platform Foundation Core - GitHub Actions Workflow
# Optimized for low-cost MVP deployment with Digital Ocean Droplets
# 
# Target: $73/month total infrastructure cost
# - DEV: $12/mo (1 vCPU, 2GB) + Supabase Free
# - STAGING: $12/mo (1 vCPU, 2GB) + Supabase Free  
# - PROD: $24/mo (2 vCPU, 4GB) + Supabase Pro $25/mo
# - GitHub Actions: Free tier (2000 min/month)
# =============================================================================

name: PF-CORE MVP Pipeline

on:
  push:
    branches: [main, develop, 'release/*']
    paths:
      - 'src/**'
      - 'app/**'
      - 'components/**'
      - 'lib/**'
      - 'tests/**'
      - 'package*.json'
      - 'Dockerfile'
      - 'docker-compose*.yml'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.vscode/**'
  pull_request:
    branches: [main, develop]
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production

env:
  NODE_VERSION: '20'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# Cancel redundant runs when new commits pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ===========================================================================
  # Stage 1: Quality Gates (Every Commit) - Target: < 3 minutes
  # ===========================================================================
  quality-gates:
    name: Quality Gates
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      coverage: ${{ steps.coverage.outputs.percentage }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Cache node_modules
        uses: actions/cache@v3
        id: node-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Install Dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci
      
      - name: Lint & Format Check
        run: |
          npm run lint
          npm run format:check
      
      - name: Type Check
        run: npm run type-check
      
      - name: Unit Tests with Coverage
        run: npm run test:unit -- --coverage --coverageReporters=json-summary
      
      - name: Extract Coverage
        id: coverage
        run: |
          COVERAGE=$(cat coverage/coverage-summary.json | jq '.total.lines.pct')
          echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT
          echo "Test coverage: $COVERAGE%"
      
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          files: ./coverage/coverage-summary.json

  # ===========================================================================
  # Stage 2: Security Scan (Parallel) - Target: < 2 minutes
  # ===========================================================================
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run Dependency Audit
        run: npm audit --audit-level=high
        continue-on-error: true
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
      
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --only-verified

  # ===========================================================================
  # Stage 3: Schema & Ontology Validation
  # ===========================================================================
  schema-validation:
    name: Schema Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Validate JSON Schemas
        run: |
          npm install -g ajv-cli
          # Validate ontology files against schema.org patterns
          for file in ontologies/*.json; do
            if [ -f "$file" ]; then
              echo "Validating $file..."
              ajv validate -s schemas/ontology-schema.json -d "$file" || true
            fi
          done
      
      - name: Validate Design Tokens
        run: |
          if [ -d "tokens" ]; then
            echo "Validating design tokens..."
            npm run validate:tokens || true
          fi

  # ===========================================================================
  # Stage 4: Integration Tests (PR Only) - Target: < 8 minutes
  # ===========================================================================
  integration:
    name: Integration Tests
    if: github.event_name == 'pull_request'
    needs: [quality-gates]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Integration Tests
        run: npm run test:integration
      
      - name: Build Application
        run: npm run build
      
      - name: Cache Build Output
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
            dist
          key: ${{ runner.os }}-build-${{ github.sha }}
      
      - name: Build Docker Image (Test)
        run: docker build -t test-image:${{ github.sha }} .

  # ===========================================================================
  # Stage 5: Deploy to Development
  # ===========================================================================
  deploy-dev:
    name: Deploy DEV
    if: github.ref == 'refs/heads/develop'
    needs: [quality-gates, security, schema-validation]
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://dev.pf-core.app
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_ENV=development
            NEXT_PUBLIC_SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
      
      - name: Deploy to DEV Droplet
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            cd /app
            echo "Pulling latest image..."
            docker compose pull
            echo "Deploying with zero-downtime..."
            docker compose up -d --no-deps --build app
            echo "Cleaning up old images..."
            docker image prune -f
            echo "DEV deployment complete!"

  # ===========================================================================
  # Stage 6: Deploy to Staging (with E2E Tests)
  # ===========================================================================
  deploy-staging:
    name: Deploy STAGING
    if: startsWith(github.ref, 'refs/heads/release/')
    needs: [quality-gates, security, schema-validation]
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.pf-core.app
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Check Coverage Gate
        if: needs.quality-gates.outputs.coverage < 80
        run: |
          echo "❌ Test coverage (${{ needs.quality-gates.outputs.coverage }}%) is below 80% threshold"
          echo "Staging deployment requires minimum 80% test coverage"
          exit 1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:staging
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:staging-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_ENV=staging
            NEXT_PUBLIC_SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
      
      - name: Deploy to STAGING Droplet
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: |
            cd /app
            echo "Pulling latest staging image..."
            docker compose -f docker-compose.staging.yml pull
            echo "Deploying to staging..."
            docker compose -f docker-compose.staging.yml up -d --no-deps --build app
            docker image prune -f
            echo "STAGING deployment complete!"
      
      - name: Setup Node.js for E2E
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install E2E Dependencies
        run: npm ci
      
      - name: Wait for Staging to be Ready
        run: |
          echo "Waiting for staging environment..."
          sleep 30
          curl --retry 10 --retry-delay 5 --retry-connrefused https://staging.pf-core.app/api/health
      
      - name: Run E2E Critical Path Tests
        run: npm run test:e2e:critical
        env:
          BASE_URL: https://staging.pf-core.app

  # ===========================================================================
  # Stage 7: Deploy to Production (Manual Gate)
  # ===========================================================================
  deploy-production:
    name: Deploy PRODUCTION
    if: github.event_name == 'release' || (github.ref == 'refs/heads/main' && github.event_name == 'push')
    needs: [quality-gates, security, schema-validation]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://app.pf-core.app
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract Version Tag
        id: version
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.tag }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:prod-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_ENV=production
            NEXT_PUBLIC_SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
      
      - name: Deploy to PRODUCTION Droplet
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd /app
            echo "Creating backup..."
            docker compose exec -T app npm run db:backup || true
            echo "Pulling latest production image..."
            docker compose -f docker-compose.prod.yml pull
            echo "Deploying to production..."
            docker compose -f docker-compose.prod.yml up -d --no-deps --build app
            docker image prune -f
            echo "PRODUCTION deployment complete!"
      
      - name: Production Smoke Tests
        run: |
          sleep 30
          curl --retry 5 --retry-delay 10 --fail https://app.pf-core.app/api/health
          echo "✅ Production smoke test passed"
      
      - name: Notify Team
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: 'Production deployment ${{ job.status == "success" && "completed ✅" || "failed ❌" }}'
          fields: repo,ref,author,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  # ===========================================================================
  # Utility: Database Migrations
  # ===========================================================================
  run-migrations:
    name: Database Migrations
    if: |
      github.ref == 'refs/heads/main' &&
      contains(github.event.head_commit.message, '[migrate]')
    needs: [quality-gates]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Run Supabase Migrations
        run: npm run db:migrate
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
